name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install linters
        run: luarocks install luacheck && luarocks install stylua

      - name: Check formatting
        run: stylua --check .

      - name: Run luacheck
        run: luacheck .
